### ISSUE TITLE
Click Effect Isn't On Top

### ISSUE THREAD

**Issue by Jacquies** [Yoshgunn/LightShadowPressRelease#11]
The click effect is in the scene rather than on top of it. For things like buttons, it causes the button itself to hide the click effect.

**Comment by Jacquies** [comment]
This has been resolved using another camera.

It is possible that we might want to come back to this and see if there's a better way to address it (shader that always writes 0 to the Z-buffer, for example).

**Comment by Yoshgunn** [comment]
Good idea. Do we have a list of all of these technical debt / optimization things?

I would re-add it as an Issue with a different Label, but I don't know how to make custom Labels...

**Comment by Yoshgunn** [comment]
Nvm. Created a custom label "Technical Debt." Feel free to use it for anything that has been fixed, but could use a fixer-upper down the road.
