### ISSUE TITLE
How Do I Dim EVERY Light?

### ISSUE THREAD

**Issue by Yoshgunn** [Yoshgunn/LightShadowPressRelease#17]
Some of the lights in Level 2-2 do not dim when then level ends. I think it's the Spot lights I made.

How can I hook them up? Their Range values should slowly decrease to 0, just like the Point lights in the scene.

**Comment by Jacquies** [comment]
The problem is that only torches are set to shrink when the level ends. But
the torch script was designed with only point lights in mind...

I can try to write a subclass of torch for spotlights, but the way torches
work now might make it difficult...

**Comment by Jacquies** [comment]
Alright, I wrote a new class (MySpotLight) which will also dim at the end
of the level. I already attached it to the spotlights in 2-2. If you need
to use a spotlight that will dim at the end of the level, just attach the
MySpotLight script to it.
